
version: 2.1

jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure back-end infrastructure exsist
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/backend.yml \
            --region us-west-2 \
            --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
            --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
            --tags project=udapeople

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - deploy-infrastructure
